-- PlayTorrio Cloud schema is defined in PlayTorrioV2:
-- https://github.com/killamfkr/PlayTorrioV2/tree/main/supabase/migrations
--
-- IPTV portals sync via `user_settings.prefs` → `iptv_pt_cloud_bundle_v1`
-- → `pt_iptv_verified_portals` (wrapped JSON), not a separate iptv_portals table.
--
-- Run these migrations in your Supabase SQL editor:
--   20260401000000_playtorrio_user_sync.sql
--   20260402000000_user_debrid_secrets.sql
--   20260403000000_user_profiles.sql
